server:
  port: 8080

spring:
  application:
    name: Film-Rating-Api
  datasource:
    url: jdbc:postgresql://localhost:5432/film_rate
    username: postgres
    password: AromanouskiJ2007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
#    show-sql: true
#    properties:
 #     hibernate:
  #    logging:
   #     level:
    #      org.hibernate.SQL: DEBUG
     #     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jmx:
    enabled: true
